variables:
  BUILD_PATH: ./out

stages:
  - build
  - deploy
  - aws-deploy

build:
  stage: build
  image: node:lts-bullseye
  tags:
    - docker-executor
    - builder
  only: &cd_refs
    refs:
      - master
  script:
    - npm config set update-notifier false
    - npm install
    - npm run build
    - npm run export
    - find ${BUILD_PATH} -type f -regextype posix-extended -regex '.+\.(js|css|html|svg)$' -exec gzip --keep --best --quiet --force {} \;
  artifacts:
    name: "CompiledProject"
    expire_in: 1 days
    paths:
      - ${BUILD_PATH}

include:
  - project: devops/templates
    file: /static/noah-domain-[prod].yml

nginx-prod:
  stage: aws-deploy
  tags:
    - nft-staking-prod
  only:
    refs:
      - master
  environment:
    name: aws-production
    url: https://${DOMAIN_NAME}
  when: manual
  script: &static_deploy
    # Files
    - mkdir --parents --verbose ${PROJECT_ROOT}/${CI_ENVIRONMENT_NAME}
    - rsync --archive --delete-after ./dist/ ${PROJECT_ROOT}/${CI_ENVIRONMENT_NAME}
    # Nginx
    - j2 .nginx.conf.j2 -o /etc/nginx/sites-available/gitlab-${CI_PROJECT_ID}-${CI_ENVIRONMENT_NAME}
    - ln --verbose --symbolic --force --no-target-directory /etc/nginx/sites-available/gitlab-${CI_PROJECT_ID}-${CI_ENVIRONMENT_NAME} /etc/nginx/sites-enabled/gitlab-${CI_PROJECT_ID}-${CI_ENVIRONMENT_NAME}
    - sudo nginx -t || ( test_result=$? && rm -f /etc/nginx/sites-enabled/gitlab-${CI_PROJECT_ID}-${CI_ENVIRONMENT_NAME} && exit ${test_result} )
    - sudo systemctl reload nginx
    # debug information
    - j2 .info.json.j2 -o ${PROJECT_ROOT}/${CI_ENVIRONMENT_NAME}/info.json
